### ISSUE TITLE
Remove port from nodeurl and clienturl (docs, sample config and examples)

### ISSUE THREAD

**Issue by macfarla** [ConsenSys/orion#419]
eg if you specify
```
nodeurl = "http://127.0.0.1:8888/"
nodeport = 7777
```
the url actually used will be http://127.0.0.1:7777
The examples, sample config and docs all make them the same eg
```
nodeurl = "http://127.0.0.1:8081/"
nodeport = 8081
```
same for clienturl/clientport

Should be eg
```
nodeurl = "http://127.0.0.1/"
nodeport = 7777
```

**Comment by Shatakshi0805** [comment]
Hi, I would like to work on this issue. Can you assign this issue to me?

**Comment by Shatakshi0805** [comment]
Hi, I would like to work on this issue.

**Comment by Shatakshi0805** [comment]
Hello sir, I have created a pull request. In the pull request all the test cases have passed except one. The test case not passed are for the docker.md file, I made changes in the file according to the mentioned issue. can you please review it?

**Comment by macfarla** [comment]
Apologies for being ambiguous in the description. We still need the `nodeport` value but remove the port from the `nodeurl` value
eg
```
nodeurl = "http://127.0.0.1/"
nodeport = 7777
```
I think if you make this change throughout, the docker step should pass.

**Comment by vmichalik** [comment]
@macfarla is this issue still relevant, or should it be closed?

**Comment by macfarla** [comment]
the easy workaround is to make them the same ie leave as is.
