### ISSUE TITLE
Lack of missing data pulling and related issues

### ISSUE THREAD

**Issue by Viserius** [ConsenSys/orion#426]
Weirdly enough, an Orion node cannot pull private data that it is missing from other Orion nodes in the same group. The ability to pull private data is an important feature for the functioning of the network, which Orion currently lacks.

Related issues:
1. Nodes that crash for whatever reason, cannot recover private data to sync up. In other words, losing your hard drive means you can never participate in the private group anymore, because your state is out-of-sync and no means exist to recover. (Yes, you could set up the database for local replication, but the responsibility/risk still lies with the node/db administrator)
2. A private transaction can only be sent if **all** nodes in a private group are available. This availability requirement easily be made less strict when nodes can sync and pull missing private data at a later point in time (deferring it), i.e. majority or 2/3rds of nodes must be online instead of all nodes.
3. Private groups, by definition, have to be rigid by design. Because nodes cannot pull private data whenever they want to, no new nodes can be added to the private groups in Besu (except if you copy the entire state over, which introduces trust due to a lack of transparency)

**Comment by vmichalik** [comment]
Hi Viserius, great to have you here and appreciate the ideas and suggestions!

In this case I think we've built something for this already. Have you checked out https://besu.hyperledger.org/en/stable/Concepts/Privacy/Flexible-PrivacyGroups/?

It allows adding new members and then they can sync the private state from their peers.

**Comment by Viserius** [comment]
Hi @vmichalik , thank you for the quick reply!
I did not give it too much of a thorough look as it was mentioned as unstable/unfinished. I am not entirely sure how it works, but by periodically "rehydrating" the private transactions (`maybeRehydrate`), will _all_ private transactions a node has not received yet be fetched and applied? If so, this would indeed solve the 1st and 3rd issue I mention. Could be useful to document that it is safer in case of failure (point 1), so users are aware of the risks of the current (legacy) approaches.

If the dehydration works as I described/expected, then this could be used to make the availability requirement less rigid as well (point 2). This would be a very strong improvement. Because if one node is unavailable right now, the entire private group is not operational (unless you already implemented this).

Thanks for the thoughts! Trying to think with you here :).

**Comment by macfarla** [comment]
High availability might be what you are looking for here Orion https://docs.orion.consensys.net/en/stable/HowTo/High-Availability/https://docs.goquorum.consensys.net/en/latest/HowTo/Configure/HighAvailability/

**Comment by Viserius** [comment]
Requiring High Availability means node operators are responsible for not losing data. This would be a workaround indeed, but still puts a high responsibility on the node operator. If for whatever reason the data of all highly available nodes and their database(s) are lost, they cannot fetch the data from other peers. While theoretically, the data is still present in the network (at nodes of other organizations/node operators). In any case, [it seems Tessera has this recovery feature](https://docs.tessera.consensys.net/en/stable/HowTo/Configure/Data-Recovery/) which would be a more elegant solution, so that would probably be the way to go.

**Comment by macfarla** [comment]
Sounds like Tessera has what you need!
